apiVersion: v1
kind: Service
metadata:
  name: mediawiki-service
  labels:
    rm: "346005"
    turma: 2CLDR
    app: mediawiki
spec:
  type: LoadBalancer
  selector:
    rm: "346005"
    turma: 2CLDR
    app: mediawiki
  ports:
    - port: 80
      targetPort: 80
